service: serverless-bolt-js
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: process.env.SIGNING_SECRET
    SLACK_BOT_TOKEN: process.env.BOT_TOKEN
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
